APP_PORT: "8080"
ENV: "development"
DATABASE_URL: "mongodb://localhost:27017"
JWT_SECRET: "leomuguchia"
LOG_LEVEL: "info"
MAX_REQUESTS_PER_MIN: 100
GOOGLE_SERVICE_ACCOUNT_FILE: "config/campus.json"


# Redis configuration
REDIS_ADDR: "localhost:6379"
REDIS_PASSWORD: ""
REDIS_CACHE_DB: 0       # For general caching
REDIS_OTP_DB: 2         # For OTP caching
